language: python
dist: trusty
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
matrix:
# cython is currently broken with these
  allow_failures:
    - python: "3.7-dev" 
  include:
     addons:
         apt:
            sources:
               - ubuntu-toolchain-r-test
            packages:
               - gfortran-6
               - gzip
  include:
     addons:
         apt:
            sources:
               - ubuntu-toolchain-r-test
            packages:
               - gfortran-7
               - gzip
  include:
     addons:
         apt:
            sources:
               - ubuntu-toolchain-r-test
            packages:
               - gfortran-5
               - gzip
  include:
     addons:
         apt:
            sources:
               - ubuntu-toolchain-r-test
            packages:
               - gfortran-4
               - gzip

install: 
  - pip install -r requirements.txt
  - pip install -e .[dev]
  - python setup.py install
# command to run tests
script: 
  - coverage run --source=gfort2py setup.py test
sudo: required
env: 
  TRAVIS=1
after_success:
    coveralls
cache: 
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
